# Data Analytics course (07-09-2026)

# pandas

# def: pandas is a open source library designed for data manipulation and analysis 
# pandas is designed over the numpy.

# importent list of operations in pandas

# data structure creation (series(1d array), dataframes (2d array))
2. data input and ouput (csv,excel,sql,json)
3. understanding the dataset (head,tail,dtype.........)
4. data filtering and indexing (loc,iloc,where().....)
5. handling of missing values(NAN/NULL)
6. removing duplicate values
7. handling inconsistant data
8. data tranformation using apply(),map()
9. aggregation and grouping
10. time series operations
11. basic data visualization

# pandas installation:

# pip install pandas
# above command can create problem with old numpy version
# conda install pandas
# conda command will update numpy also with pandas. so no issue

# data structure creation

In [9]:
import pandas as pd

In [10]:
# conver the numpy array into series
import numpy as np
arr1 = np.array([10,20,30,40,50])
print(arr1,type(arr1))

[10 20 30 40 50] <class 'numpy.ndarray'>

In [11]:
ser3 = pd.Series([10,20,30,40,50])
print(ser3,type(ser3))

0    10
1    20
2    30
3    40
4    50
dtype: int64 <class 'pandas.core.series.Series'>

In [12]:
ser3 = pd.Series(arr1,index=['a','b','c','d','e'])
print(ser3,type(ser3))
print(ser3['a'])

a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10

In [8]:
# update operation on series(if index is already exsts)
ser3[3] = 100000

# insert new value
ser3[5] = 2000
ser3['a'] = 5000
ser3[60] = 7000
ser3[3.4] = 8000

NameError: name 'ser3' is not defined

# Dataframe (2d array)

# data frame is a 2d array, store data in form of matrix

# creating dataframe

In [3]:
import pandas as pd

In [6]:
df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [8]:
# converting list to dataframe
fruit_list = ["Aratipandu", "Mamidipandu", "kamalapandu", "Drakshapandu"]

df = pd.DataFrame(fruit_list, columns = ["Fruits Name"])
print(df)

    Fruits Name
0    Aratipandu
1   Mamidipandu
2   kamalapandu
3  Drakshapandu

In [16]:
# converting 2d list to dataframe

fruits_list = [["Aratipandu",40], ["Mamidipandu",1000], ["Kamalapandu",10], ["Drakshapandu",120]]

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price"])
df

     Fruit Name  Price
0    Aratipandu     40
1   Mamidipandu   1000
2   Kamalapandu     10
3  Drakshapandu    120

In [17]:
# created three columns dataframes
fruits_list = [["Aratipandu",40,100], ["Mamidipandu",1000,200], ["Kamalapandu", 10,1000], ["Drakshapandu",120,20]]

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    Aratipandu     40       100
1   Mamidipandu   1000       200
2   Kamalapandu     10      1000
3  Drakshapandu    120        20

In [20]:
fruits_list = {("Aratipandu",40,100), ("Mamidipandu",1000,200), ("Kamalapandu", 10,1000), ("Drakshapandu",120,20)}

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0  Drakshapandu    120        20
1    Aratipandu     40       100
2   Kamalapandu     10      1000
3   Mamidipandu   1000       200

In [21]:
# creating dataframe from set of set

# in set, we cannot store the mutable items
# in set only immutable items can be stored.

fruits_list = {{"Aratipandu",40,100}, {"Mamidipandu",1000,200}, {"Kamalapandu", 10,1000}, {"Drakshapandu",120,20}}

df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

TypeError: unhashable type: 'set'

In [27]:
# creating the dataframe from dictionary:

student_data = {
    "Name" : ["Sujitha", "Prabhavathi", "Raja", "Srikanth", "Vemuri"],
    "salary" : [40, 50, 60, 15, 25],
    "Study_time" : [12,14,16,1,5]
}

df = pd.DataFrame(student_data)
df

          Name  salary  Study_time
0      Sujitha      40          12
1  Prabhavathi      50          14
2         Raja      60          16
3     Srikanth      15           1
4       Vemuri      25           5

# 2. Data input and output (CSV, EXCEL, SQL, JSON)

In [28]:
# importing data from CSV file

import os
os.getcwd()

'C:\\Users\\DELL'

In [29]:
# import a csv file as dataframe

df_csv = pd.read_csv("CSV_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [30]:
# import excel file as a dataframe

df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [13]:
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [9]:
# reading and writing in a sql table:

import sqlite3

# creating a database if it don't exist
conn = sqlite3.connect("Profession.db")

In [14]:
# creating a table and storing the dataframe data inside it.
df.to_sql("Prof_table", conn, if_exists = "replace")

500

In [16]:
# reading the data from sql table to df
df =pd.read_sql("select * from prof_table", conn)
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

In [17]:
# importing data from json file:

df_json = pd.read_json("json_data.json")
df_json

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [19]:
# exporting 
df_json.to_json("foodData_da22.json")

# understanding the datasets

In [20]:
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

In [24]:
# view the data with head(),tail() functions
# head(x) function is used for accessing top records.
# head function by default shows only 5 records


import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [26]:
df.tail()

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [27]:
# shape of dataframe
df.shape

(500, 6)

In [30]:
# show the single column
df['Name']

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [31]:
df.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [34]:
df.Profession

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [36]:
df[["Name", "Profession"]]

          Name         Profession
0       olivia            Teacher
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [38]:
# printing multiple columns:
df[["Name", "Profession", "salary"]]

          Name         Profession  salary
0       olivia            Teacher  184518
1    sophia                 Boxer  119572
2         jake          Scientist  174897
3        Rocky               Chef  117920
4        Rocky               Chef  117920
..         ...                ...     ...
495       John              Boxer  137929
496   Sherlock              Boxer   39870
497   Sherlock          Detective  165951
498     Olivia           Comedian  192618
499   Sherlock  Software Engineer  194886

[500 rows x 3 columns]

In [40]:
# renameing the column names:
df_rename = df.rename(columns = {'Name' : 'Peru', 'Profession' : 'Vruthi'})
df_rename

      ID       Peru   Age             Vruthi  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [41]:
# print all the column names

df_rename.columns

Index(['ID', 'Peru', 'Age', 'Vruthi', 'salary', 'Marriage_proposal_count'], dtype='object')

##### creating a new column in the dataframe

In [52]:
# Here, the rank function is a pandas function
# The rank function gives rank 1 to the minimum salary and a higher rank value to higher salaries

df['rank123'] = df['salary'].rank(ascending = False)
df.sort_values('rank')

# sort_values() sorts the dataframe based on a column value.

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,rank123
213,214,Sherlock,21.0,Chef,30164,2,1.0,500.0
90,91,Rocky,43.0,Software Engineer,30407,10,2.0,499.0
398,399,Rocky,25.0,Scientist,30659,5,3.0,498.0
329,330,Sherlock,40.0,Scientist,30905,0,4.0,497.0
284,285,Jake,46.0,Detective,30971,1,5.0,496.0
...,...,...,...,...,...,...,...,...
474,475,Sophia,30.0,Doctor,198653,1,496.0,5.0
167,168,Mr. Bean,44.0,Comedian,198847,14,497.0,4.0
132,133,Rocky,31.0,Doctor,198978,8,498.0,3.0
65,66,Emma,57.0,Pilot,199317,1,499.0,2.0
436,437,Sherlock,52.0,Boxer,199529,3,500.0,1.0

In [53]:
# Deleting the column
# axis =1: delete the column
# axis =0: delete the row

df = df.drop(['rank123', 'rank'], axis = 1)
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

##### Replace a value in dataframe

In [13]:
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [14]:
df['Name'] = df.Name.replace("olivia","Rakul")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1      Rakul  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [15]:
# replacing multiple values together
df['Name'] = df.Name.replace({"Rakul": "Sujitha", "Raja" : "Bharath"})

# replacing values from multiple columns together
# inplace = True : to perform the task without taking extra space
df.replace({"Raja" : "Mahesh", "Teacher" : "Upadhaye"}, inplace = True)
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1    Sujitha  23.0           Upadhaye  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [16]:
# dtypes are used to check the data types of all the columns
# in pandas, strings are represented with object
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

### convert datatype

In [17]:
df['Name'] = df['Name'].astype("string")
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                              int64
Marriage_proposal_count             int64
dtype: object

In [19]:
df['salary'] = df['salary'].astype("float")
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                            float64
Marriage_proposal_count             int64
dtype: object

In [20]:
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Sujitha,23.0,Upadhaye,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [21]:
# printing the columns which is having specific datatypes

df.select_dtypes(include = ['object', 'string'])

          Name         Profession
0      Sujitha           Upadhaye
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [22]:
# give name of all the columns which are string type
df.select_dtypes(include = ['object', 'string']).columns

Index(['Name', 'Profession'], dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    string
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    float64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(2), int64(2), object(1), string(1)
memory usage: 23.6+ KB

In [28]:
# Query: print all the unique professions

df.Profession.unique()

array(['Upadhaye', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [29]:
# nunique is telling us the number if unique value
df.Profession.nunique()

10

In [30]:
# Query: how many people are boxer in this dataset

df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Upadhaye             45
Detective            45
Artist               41
Name: count, dtype: int64

In [33]:
# Describe statistical information
# by default, describe() works on numercial columns

df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [34]:
# describing the string/object columns

df.describe(include = ["object", "string"])

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

# Data filtering and indexing (loc,iloc,where())

In [37]:
# query: filter all the records  where salary > 100000
df.salary > 100000

0       True
1       True
2       True
3       True
4       True
       ...
495     True
496    False
497     True
498     True
499     True
Name: salary, Length: 500, dtype: bool

In [38]:
df[df.salary > 100000]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Sujitha,23.0,Upadhaye,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
493,494,Sophia,39.0,Doctor,174500.0,0
495,496,John,45.0,Boxer,137929.0,0
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [39]:
# Query : filter all the records where salary > 100000 & salary < 150000

df[df.salary > 100000 & 150000]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Sujitha,23.0,Upadhaye,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929.0,0
496,497,Sherlock,46.0,Boxer,39870.0,6
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [40]:
df[(df.salary > 100000) & (df.salary < 150000)]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
1,2,sophia,20.0,Boxer,119572.0,2
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
5,4,Rocky,56.0,Chef,117920.0,3
6,4,Rocky,56.0,Chef,117920.0,11
...,...,...,...,...,...,...
469,470,Sophia,42.0,Software Engineer,102357.0,0
480,481,Sherlock,22.0,Detective,126604.0,0
483,484,Olivia,59.0,Artist,124648.0,2
491,492,Emma,34.0,Artist,145412.0,1
495,496,John,45.0,Boxer,137929.0,0

In [42]:
# Query : filter all the records where salary < 100000 | or salary > 150000

df[(df.salary > 100000) | (df.salary > 150000)]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Sujitha,23.0,Upadhaye,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
493,494,Sophia,39.0,Doctor,174500.0,0
495,496,John,45.0,Boxer,137929.0,0
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [ ]:
# Query: find the person record who is getting highest salary.
Hint: max()