In [1]:
# Query : Find the person record who is getting highest salary.
# hint : max()
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [2]:
# Query : Find the person record who is getting highest salary.
max(df.salary)

199529

In [3]:
df[df.salary == df.salary.max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

In [4]:
# Query: Find the person record who is getting lowest salary.
# Hint: min()

min(df.salary)

30164

In [5]:
df[df.salary == df.salary.min()]

      ID      Name   Age Profession  salary  Marriage_proposal_count
213  214  Sherlock  21.0       Chef   30164                        2

In [6]:
df.salary == df.salary.min()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: salary, Length: 500, dtype: bool

In [7]:
df.salary == df.salary.max()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: salary, Length: 500, dtype: bool

In [11]:
# Query : print just the name,age, salary of the person having max salary
df[df.salary == df.salary.max()][["Name", "Age","salary"]]

         Name   Age  salary
436  Sherlock  52.0  199529

In [10]:
df["Name"]

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [14]:
df[["Name", "Age"]]

          Name   Age
0       olivia  23.0
1    sophia     20.0
2         jake  38.0
3        Rocky  56.0
4        Rocky  56.0
..         ...   ...
495       John  45.0
496   Sherlock  46.0
497   Sherlock  47.0
498     Olivia  55.0
499   Sherlock  59.0

[500 rows x 2 columns]

In [15]:
df[["salary", "Age", "Name"]]

     salary   Age       Name
0    184518  23.0     olivia
1    119572  20.0  sophia
2    174897  38.0       jake
3    117920  56.0      Rocky
4    117920  56.0      Rocky
..      ...   ...        ...
495  137929  45.0       John
496   39870  46.0   Sherlock
497  165951  47.0   Sherlock
498  192618  55.0     Olivia
499  194886  59.0   Sherlock

[500 rows x 3 columns]

### where()

In [22]:
### where() : used for filtering the data
# where() function returns NaN in place of those values
# which don't statisfied the condition

df1 = df.copy()
df1 = df1.Age.where(df1.Age > 50,1)
df1

0       1.0
1       1.0
2       1.0
3      56.0
4      56.0
       ...
495     1.0
496     1.0
497     1.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [19]:
# if you dont want NaN records
df[df.Age > 50]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

# indexing: loc & iloc

In [23]:
# loc & iloc is used for filtering
# these helps to select particular row and column in the dataframe

In [29]:
# Query: print records 1 to 4 and columns id, name, age only.
df.loc[1:4, 'ID': 'Age'] # df.loc[start_row : end_row, col_start: col_end]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0

# Interview Question
Q: What is the difference between loc and iloc?
Ans:1. In loc columns are passed with their names but in iloccolumns are passed as index
2. iloc is easy to use due to index usage
3. iloc[start_ro: end_row-1, col_start : col_end-1]
4. iloc is little faster than the loc

In [28]:
# Query: print records 10 to 40, and columns Name:profession only.

df.loc[10:40, "Name" : "Profession"]

        Name   Age         Profession
10     Rocky   NaN             Doctor
11      Jake   NaN             Artist
12    Olivia  22.0           Comedian
13      John  46.0             Artist
14      Jake  40.0               Chef
15  Sherlock  30.0              Boxer
16      Jake  46.0             Artist
17      Jake  53.0  Software Engineer
18     Rocky  25.0           Comedian
19  Sherlock  40.0          Detective
20  Sherlock  40.0          Detective
21      John  41.0          Scientist
22      John  41.0          Scientist
23  Sherlock  42.0              Boxer
24    Olivia  60.0          Detective
25    Olivia  53.0          Detective
26     Alice  48.0              Pilot
27  Sherlock  55.0          Scientist
28     Alice  21.0               Chef
29     Alice  21.0               Chef
30     Alice  30.0            Teacher
31    Olivia  30.0             Doctor
32  Mr. Bean  27.0             Artist
33    Olivia  45.0           Comedian
34  Sherlock  46.0               Chef
35  Mr. Bean  44.0           Comedian
36     Rocky  57.0            Teacher
37  Mr. Bean  32.0          Scientist
38      John  27.0  Software Engineer
39    Olivia  60.0  Software Engineer
40     Alice  52.0               Chef

In [30]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [31]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [32]:
# Query: print records 1 to 4, and columns ID, Name, Age only.
df.iloc[1:5, 0:3]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0