In [2]:
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [3]:
df.iloc[0:20, 0:5]

    ID       Name   Age         Profession  salary
0    1     olivia  23.0            Teacher  184518
1    2  sophia     20.0              Boxer  119572
2    3       jake  38.0          Scientist  174897
3    4      Rocky  56.0               Chef  117920
4    4      Rocky  56.0               Chef  117920
5    4      Rocky  56.0               Chef  117920
6    4      Rocky  56.0               Chef  117920
7    4      Rocky  56.0               Chef  117920
8    4      Rocky  56.0               Chef  117920
9    4      Rocky  56.0               Chef  117920
10  11      Rocky   NaN             Doctor   75543
11  12       Jake   NaN             Artist  174780
12  13     Olivia  22.0           Comedian  102063
13  14       John  46.0             Artist   43078
14  15       Jake  40.0               Chef  171553
15  16   Sherlock  30.0              Boxer   57774
16  17       Jake  46.0             Artist  135907
17  18       Jake  53.0  Software Engineer  127117
18  19      Rocky  25.0           Comedian  181312
19  20   Sherlock  40.0          Detective  118998

In [4]:
# iloc using step size
df.iloc[0:200:10, 0:5:2]

      ID   Age  salary
0      1  23.0  184518
10    11   NaN   75543
20    21  40.0  118998
30    31  30.0   77599
40    41  52.0   46535
50    51  42.0  105830
60    61  37.0  106436
70    71  40.0  188182
80    81  38.0  125743
90    91  43.0   30407
100  101  60.0  163578
110  111  44.0  165346
120  121  43.0   34630
130  131  26.0  145227
140  141  46.0   61653
150  151  60.0  135857
160  161  42.0  150873
170  171  30.0  139649
180  181  32.0  134405
190  191  34.0  112912

In [5]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [6]:
# iloc showing any random columns
df.iloc[0:200:10, [1,4]]

         Name  salary
0      olivia  184518
10      Rocky   75543
20   Sherlock  118998
30      Alice   77599
40      Alice   46535
50       Liam  105830
60   Sherlock  106436
70       Jake  188182
80       Emma  125743
90      Rocky   30407
100    Olivia  163578
110      John  165346
120  Mr. Bean   34630
130  Mr. Bean  145227
140      John   61653
150  Sherlock  135857
160     Rocky  150873
170  Mr. Bean  139649
180    Sophia  134405
190    Sophia  112912

In [7]:
df.iloc[1:10, [1,3,4]]

        Name   Profession  salary
1  sophia           Boxer  119572
2       jake    Scientist  174897
3      Rocky         Chef  117920
4      Rocky         Chef  117920
5      Rocky         Chef  117920
6      Rocky         Chef  117920
7      Rocky         Chef  117920
8      Rocky         Chef  117920
9      Rocky         Chef  117920

In [8]:
# iloc to get specific value
print(df.iloc[1,5])

2

In [9]:
# loc to get age and salary columns
df.loc[0:5, ["Age", "salary"]]

    Age  salary
0  23.0  184518
1  20.0  119572
2  38.0  174897
3  56.0  117920
4  56.0  117920
5  56.0  117920

In [11]:
# Comparision condition inside the loc
df.Age > 50

0      False
1      False
2      False
3       True
4       True
       ...
495    False
496    False
497    False
498     True
499     True
Name: Age, Length: 500, dtype: bool

In [12]:
# comparision condition inside the loc

df.loc[df.Age > 50, ["Age", "salary"]]

      Age  salary
3    56.0  117920
4    56.0  117920
5    56.0  117920
6    56.0  117920
7    56.0  117920
..    ...     ...
489  56.0   41192
490  57.0  154180
492  55.0   57720
498  55.0  192618
499  59.0  194886

[126 rows x 2 columns]

In [15]:
# salary of people Age > 50 & Age < 70
df.loc[(df.Age > 50) & (df.Age < 70) ,["Age", "salary"]]

      Age  salary
3    56.0  117920
4    56.0  117920
5    56.0  117920
6    56.0  117920
7    56.0  117920
..    ...     ...
489  56.0   41192
490  57.0  154180
492  55.0   57720
498  55.0  192618
499  59.0  194886

[126 rows x 2 columns]

In [18]:
# iloc don't works with pandas series
# .values will convert it into numpy array
df.iloc[(df.Age > 50).values, 0:4]

      ID      Name   Age         Profession
3      4     Rocky  56.0               Chef
4      4     Rocky  56.0               Chef
5      4     Rocky  56.0               Chef
6      4     Rocky  56.0               Chef
7      4     Rocky  56.0               Chef
..   ...       ...   ...                ...
489  490      John  56.0          Scientist
490  491      John  57.0              Pilot
492  493      John  55.0             Artist
498  499    Olivia  55.0           Comedian
499  500  Sherlock  59.0  Software Engineer

[126 rows x 4 columns]

In [20]:
df.iloc[(df.Age > 50), 0:4]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [21]:
type((df.Age > 50).values)

numpy.ndarray

### updating a value inside the dataframe

In [25]:
# replace/update all the age > 50 with 18
df[df.Age > 50]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

In [26]:
df[df.Age > 50].Age

3      56.0
4      56.0
5      56.0
6      56.0
7      56.0
       ...
489    56.0
490    57.0
492    55.0
498    55.0
499    59.0
Name: Age, Length: 126, dtype: float64

In [27]:
df.loc[df.Age > 50, "Age"] = 18

In [28]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  18.0               Chef  117920                        2
4      4      Rocky  18.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  18.0           Comedian  192618                        5
499  500   Sherlock  18.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [29]:
### at & iat for single value access
# at and iat is faster than loc and iloc

df.at[0, "Name"] = "Mahesh babu"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Mahesh babu,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

In [32]:
df.iat[0,1] = "vijay devarkonda"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,vijay devarkonda,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

### sorting rows in dataframes

In [33]:
df.sort_values('Age')

      ID      Name   Age         Profession  salary  Marriage_proposal_count
499  500  Sherlock  18.0  Software Engineer  194886                       28
316  317     Alice  18.0           Comedian  102420                        0
309  310      John  18.0  Software Engineer  175585                        5
297  298      Emma  18.0          Scientist  143154                        1
290  291     Rocky  18.0             Doctor  166138                        5
..   ...       ...   ...                ...     ...                      ...
46    47  Mr. Bean   NaN             Artist  190559                        5
71    72      Emma   NaN              Pilot   49986                        3
72    73    Sophia   NaN             Artist   86741                        1
73    74     Rocky   NaN  Software Engineer  159260                        0
74    75  Sherlock   NaN          Detective  165463                        0

[500 rows x 6 columns]

In [37]:
df1 = df.sort_values('Name' , ascending = False)

In [38]:
df1

      ID              Name   Age   Profession  salary  Marriage_proposal_count
0      1  vijay devarkonda  23.0      Teacher  184518                        0
1      2         sophia     20.0        Boxer  119572                        2
2      3              jake  38.0    Scientist  174897                        1
43    44            Sophia  18.0      Teacher  172273                        2
405  406            Sophia  29.0       Artist   67411                        8
..   ...               ...   ...          ...     ...                      ...
152  153             Alice  18.0      Teacher   34825                        0
416  417             Alice  33.0      Teacher   94768                        4
153  154             Alice  18.0        Boxer   31088                       11
154  155             Alice  25.0       Artist   32961                        5
296  297             Alice  22.0       Artist  180368                        3

[500 rows x 6 columns]

In [41]:
# SORT INDEX() IS USED to sort index of dataframes
df1.sort_index()

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,vijay devarkonda,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

In [42]:
df1.sort_index(inplace = True)
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,vijay devarkonda,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

### 5. Handling of missing values(NaN/Null)

# Def: Null/NaN values are missing values.
# Null is different from zero(0).
# if there is null values in the data then wrong analysis will happen.

In [1]:
# finding the null values in dataframe:
import pandas as pd

In [2]:
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [4]:
df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [5]:
# check which column have how many null values.
df.isnull()

        ID   Name    Age  Profession  salary  Marriage_proposal_count
0    False  False  False       False   False                    False
1    False  False  False       False   False                    False
2    False  False  False       False   False                    False
3    False  False  False       False   False                    False
4    False  False  False       False   False                    False
..     ...    ...    ...         ...     ...                      ...
495  False  False  False       False   False                    False
496  False  False  False       False   False                    False
497  False  False  False       False   False                    False
498  False  False  False       False   False                    False
499  False  False  False       False   False                    False

[500 rows x 6 columns]

In [6]:
# records with null values
df[df.Age.isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [9]:
df.Age.isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Age, Length: 500, dtype: bool

In [10]:
df.Age

0      23.0
1      20.0
2      38.0
3      56.0
4      56.0
       ...
495    45.0
496    46.0
497    47.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [11]:
df1 = df.copy()

# delete the recordds which is having null values
# how = 'any' : if even a single value is null then delete the column.
# how = "all" : delete column only if all values in the column is null.
df1 = df1.dropna()
df1

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[492 rows x 6 columns]

In [13]:
df1.shape

(492, 6)

In [17]:
df2 = df.copy()

# delete the columns with null value.
# how = 'any' : if even a single value is null then delete the column.
# how = "all" : delete column only if all values in the column is null
df2 = df2.dropna(axis = 1)
df2

      ID       Name         Profession  salary  Marriage_proposal_count
0      1     olivia            Teacher  184518                        0
1      2  sophia                 Boxer  119572                        2
2      3       jake          Scientist  174897                        1
3      4      Rocky               Chef  117920                        2
4      4      Rocky               Chef  117920                        1
..   ...        ...                ...     ...                      ...
495  496       John              Boxer  137929                        0
496  497   Sherlock              Boxer   39870                        6
497  498   Sherlock          Detective  165951                        5
498  499     Olivia           Comedian  192618                        5
499  500   Sherlock  Software Engineer  194886                       28

[500 rows x 5 columns]

In [20]:
# replacing the null values with some other value

df3 = df.copy()
df3.Age = df3.Age.fillna(23)
df3.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

# Finding & Handling duplicate values

In [23]:
# finding number of duplicate records
df.duplicated().sum()

np.int64(3)

In [24]:
# 2nd and more duplicated
# complete record is matching with some other record.
df[df.duplicated()]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [25]:
# showing all the duplicate records.
df[df.duplicated(keep = False)]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [28]:
# finding duplicates based upon specific columns.
#Query: count all the records where age & salary is matching/duplicate
df [df.duplicated(keep = False, subset = ['Name', 'Profession', 'salary'])].count()

ID                         13
Name                       13
Age                        13
Profession                 13
salary                     13
Marriage_proposal_count    13
dtype: int64

In [34]:
# deleting duplicate values
df4 = df.copy()

df4 = df4.drop_duplicates()
df4.duplicated().sum()

np.int64(0)

In [36]:
df4.shape

(497, 6)

In [37]:
# delete specific column based duplicate records
df5 = df.copy()
df5 = df5.drop_duplicates(subset = ['Age', 'salary'])
df5.shape

(491, 6)

In [40]:
df.duplicated(subset = ['Age', 'salary']).count()

np.int64(500)

In [41]:
df.duplicated(subset = ['Age', 'salary']).sum()

np.int64(9)

# Handling the inconsistant data

In [45]:
# in our dataset, name of the columns are inconsistant.
# lets make all the column names start with capital letter.

df.columns = df.columns.str.title()

In [46]:
df.columns

Index(['Id', 'Name', 'Age', 'Profession', 'Salary', 'Marriage_Proposal_Count'], dtype='object')

In [50]:
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [51]:
df.Name = df.Name.str.title()
df.Name.unique()

array(['Olivia', 'Sophia   ', 'Jake', 'Rocky', 'John', 'Sherlock',
       'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'], dtype=object)

In [52]:
df.Name = df.Name.str.lower()
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'rocky', 'john', 'sherlock',
       'alice', 'mr. bean', 'sophia', 'liam', 'emma'], dtype=object)

In [53]:
df.Name = df.Name.str.strip()
df.Name.unique()

array(['olivia', 'sophia', 'jake', 'rocky', 'john', 'sherlock', 'alice',
       'mr. bean', 'liam', 'emma'], dtype=object)

In [54]:
df

      Id      Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1    olivia  23.0            Teacher  184518                        0
1      2    sophia  20.0              Boxer  119572                        2
2      3      jake  38.0          Scientist  174897                        1
3      4     rocky  56.0               Chef  117920                        2
4      4     rocky  56.0               Chef  117920                        1
..   ...       ...   ...                ...     ...                      ...
495  496      john  45.0              Boxer  137929                        0
496  497  sherlock  46.0              Boxer   39870                        6
497  498  sherlock  47.0          Detective  165951                        5
498  499    olivia  55.0           Comedian  192618                        5
499  500  sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [55]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [56]:
df.Profession = df.Profession.str.strip()
df.Profession.unique()

array(['Teacher', 'Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

# Data transformation using apply() & map()

In [57]:
# Query: double the salary of the employees

df6 = df.copy()

df6.columns

Index(['Id', 'Name', 'Age', 'Profession', 'Salary', 'Marriage_Proposal_Count'], dtype='object')

In [63]:
df6.Salary = df6.Salary.apply(lambda x : x * 2)
df6.Salary

0      2952288
1      1913152
2      2798352
3      1886720
4      1886720
        ...
495    2206864
496     637920
497    2655216
498    3081888
499    3118176
Name: Salary, Length: 500, dtype: int64

In [61]:
df.Salary

0      184518
1      119572
2      174897
3      117920
4      117920
        ...
495    137929
496     39870
497    165951
498    192618
499    194886
Name: Salary, Length: 500, dtype: int64

In [65]:
df6

      Id      Name   Age         Profession   Salary  Marriage_Proposal_Count
0      1    olivia  23.0            Teacher  2952288                        0
1      2    sophia  20.0              Boxer  1913152                        2
2      3      jake  38.0          Scientist  2798352                        1
3      4     rocky  56.0               Chef  1886720                        2
4      4     rocky  56.0               Chef  1886720                        1
..   ...       ...   ...                ...      ...                      ...
495  496      john  45.0              Boxer  2206864                        0
496  497  sherlock  46.0              Boxer   637920                        6
497  498  sherlock  47.0          Detective  2655216                        5
498  499    olivia  55.0           Comedian  3081888                        5
499  500  sherlock  59.0  Software Engineer  3118176                       28

[500 rows x 6 columns]

In [69]:
# Query2: create a new column which divide the employees as senior and junior
# based upon the salary. if the salary > 3000000 : senior otherwise that person is junior


# use of apply() function on complete dataframe.
df6['Position'] = df6.apply(lambda row : 'Senior' if row['Salary'] > 300000 else 'Junior', axis = 1)
df6

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Position
0,1,olivia,23.0,Teacher,2952288,0,Senior
1,2,sophia,20.0,Boxer,1913152,2,Senior
2,3,jake,38.0,Scientist,2798352,1,Senior
3,4,rocky,56.0,Chef,1886720,2,Senior
4,4,rocky,56.0,Chef,1886720,1,Senior
...,...,...,...,...,...,...,...
495,496,john,45.0,Boxer,2206864,0,Senior
496,497,sherlock,46.0,Boxer,637920,6,Senior
497,498,sherlock,47.0,Detective,2655216,5,Senior
498,499,olivia,55.0,Comedian,3081888,5,Senior
499,500,sherlock,59.0,Software Engineer,3118176,28,Senior

In [ ]:
# Query: create a new column divide the employees into categories old and young.
# if age > 40 old and age < 40 young
df6['Ca