In [2]:
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [3]:
df.iloc[0:20, 0:5]

    ID       Name   Age         Profession  salary
0    1     olivia  23.0            Teacher  184518
1    2  sophia     20.0              Boxer  119572
2    3       jake  38.0          Scientist  174897
3    4      Rocky  56.0               Chef  117920
4    4      Rocky  56.0               Chef  117920
5    4      Rocky  56.0               Chef  117920
6    4      Rocky  56.0               Chef  117920
7    4      Rocky  56.0               Chef  117920
8    4      Rocky  56.0               Chef  117920
9    4      Rocky  56.0               Chef  117920
10  11      Rocky   NaN             Doctor   75543
11  12       Jake   NaN             Artist  174780
12  13     Olivia  22.0           Comedian  102063
13  14       John  46.0             Artist   43078
14  15       Jake  40.0               Chef  171553
15  16   Sherlock  30.0              Boxer   57774
16  17       Jake  46.0             Artist  135907
17  18       Jake  53.0  Software Engineer  127117
18  19      Rocky  25.0           Comedian  181312
19  20   Sherlock  40.0          Detective  118998

In [4]:
# iloc using step size
df.iloc[0:200:10, 0:5:2]

      ID   Age  salary
0      1  23.0  184518
10    11   NaN   75543
20    21  40.0  118998
30    31  30.0   77599
40    41  52.0   46535
50    51  42.0  105830
60    61  37.0  106436
70    71  40.0  188182
80    81  38.0  125743
90    91  43.0   30407
100  101  60.0  163578
110  111  44.0  165346
120  121  43.0   34630
130  131  26.0  145227
140  141  46.0   61653
150  151  60.0  135857
160  161  42.0  150873
170  171  30.0  139649
180  181  32.0  134405
190  191  34.0  112912

In [5]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [6]:
# iloc showing any random columns
df.iloc[0:200:10, [1,4]]

         Name  salary
0      olivia  184518
10      Rocky   75543
20   Sherlock  118998
30      Alice   77599
40      Alice   46535
50       Liam  105830
60   Sherlock  106436
70       Jake  188182
80       Emma  125743
90      Rocky   30407
100    Olivia  163578
110      John  165346
120  Mr. Bean   34630
130  Mr. Bean  145227
140      John   61653
150  Sherlock  135857
160     Rocky  150873
170  Mr. Bean  139649
180    Sophia  134405
190    Sophia  112912

In [7]:
df.iloc[1:10, [1,3,4]]

        Name   Profession  salary
1  sophia           Boxer  119572
2       jake    Scientist  174897
3      Rocky         Chef  117920
4      Rocky         Chef  117920
5      Rocky         Chef  117920
6      Rocky         Chef  117920
7      Rocky         Chef  117920
8      Rocky         Chef  117920
9      Rocky         Chef  117920

In [8]:
# iloc to get specific value
print(df.iloc[1,5])

2

In [9]:
# loc to get age and salary columns
df.loc[0:5, ["Age", "salary"]]

    Age  salary
0  23.0  184518
1  20.0  119572
2  38.0  174897
3  56.0  117920
4  56.0  117920
5  56.0  117920

In [11]:
# Comparision condition inside the loc
df.Age > 50

0      False
1      False
2      False
3       True
4       True
       ...
495    False
496    False
497    False
498     True
499     True
Name: Age, Length: 500, dtype: bool

In [12]:
# comparision condition inside the loc

df.loc[df.Age > 50, ["Age", "salary"]]

      Age  salary
3    56.0  117920
4    56.0  117920
5    56.0  117920
6    56.0  117920
7    56.0  117920
..    ...     ...
489  56.0   41192
490  57.0  154180
492  55.0   57720
498  55.0  192618
499  59.0  194886

[126 rows x 2 columns]

In [15]:
# salary of people Age > 50 & Age < 70
df.loc[(df.Age > 50) & (df.Age < 70) ,["Age", "salary"]]

      Age  salary
3    56.0  117920
4    56.0  117920
5    56.0  117920
6    56.0  117920
7    56.0  117920
..    ...     ...
489  56.0   41192
490  57.0  154180
492  55.0   57720
498  55.0  192618
499  59.0  194886

[126 rows x 2 columns]

In [18]:
# iloc don't works with pandas series
# .values will convert it into numpy array
df.iloc[(df.Age > 50).values, 0:4]

      ID      Name   Age         Profession
3      4     Rocky  56.0               Chef
4      4     Rocky  56.0               Chef
5      4     Rocky  56.0               Chef
6      4     Rocky  56.0               Chef
7      4     Rocky  56.0               Chef
..   ...       ...   ...                ...
489  490      John  56.0          Scientist
490  491      John  57.0              Pilot
492  493      John  55.0             Artist
498  499    Olivia  55.0           Comedian
499  500  Sherlock  59.0  Software Engineer

[126 rows x 4 columns]

In [20]:
df.iloc[(df.Age > 50), 0:4]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [21]:
type((df.Age > 50).values)

numpy.ndarray

### updating a value inside the dataframe

In [25]:
# replace/update all the age > 50 with 18
df[df.Age > 50]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

In [26]:
df[df.Age > 50].Age

3      56.0
4      56.0
5      56.0
6      56.0
7      56.0
       ...
489    56.0
490    57.0
492    55.0
498    55.0
499    59.0
Name: Age, Length: 126, dtype: float64

In [27]:
df.loc[df.Age > 50, "Age"] = 18

In [28]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  18.0               Chef  117920                        2
4      4      Rocky  18.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  18.0           Comedian  192618                        5
499  500   Sherlock  18.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [29]:
### at & iat for single value access
# at and iat is faster than loc and iloc

df.at[0, "Name"] = "Mahesh babu"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Mahesh babu,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

In [32]:
df.iat[0,1] = "vijay devarkonda"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,vijay devarkonda,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

### sorting rows in dataframes

In [33]:
df.sort_values('Age')

      ID      Name   Age         Profession  salary  Marriage_proposal_count
499  500  Sherlock  18.0  Software Engineer  194886                       28
316  317     Alice  18.0           Comedian  102420                        0
309  310      John  18.0  Software Engineer  175585                        5
297  298      Emma  18.0          Scientist  143154                        1
290  291     Rocky  18.0             Doctor  166138                        5
..   ...       ...   ...                ...     ...                      ...
46    47  Mr. Bean   NaN             Artist  190559                        5
71    72      Emma   NaN              Pilot   49986                        3
72    73    Sophia   NaN             Artist   86741                        1
73    74     Rocky   NaN  Software Engineer  159260                        0
74    75  Sherlock   NaN          Detective  165463                        0

[500 rows x 6 columns]

In [37]:
df1 = df.sort_values('Name' , ascending = False)

In [38]:
df1

      ID              Name   Age   Profession  salary  Marriage_proposal_count
0      1  vijay devarkonda  23.0      Teacher  184518                        0
1      2         sophia     20.0        Boxer  119572                        2
2      3              jake  38.0    Scientist  174897                        1
43    44            Sophia  18.0      Teacher  172273                        2
405  406            Sophia  29.0       Artist   67411                        8
..   ...               ...   ...          ...     ...                      ...
152  153             Alice  18.0      Teacher   34825                        0
416  417             Alice  33.0      Teacher   94768                        4
153  154             Alice  18.0        Boxer   31088                       11
154  155             Alice  25.0       Artist   32961                        5
296  297             Alice  22.0       Artist  180368                        3

[500 rows x 6 columns]

In [41]:
# SORT INDEX() IS USED to sort index of dataframes
df1.sort_index()

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,vijay devarkonda,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

In [42]:
df1.sort_index(inplace = True)
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,vijay devarkonda,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

In [44]:
# used to set a column as a index of dataframe
df1.set_index('ID', inplace = True)

KeyError: "None of ['ID'] are in the columns"