### Merge two dataframes

In [4]:
import pandas as pd

# def: merge two dataframes based upon common column.
# functions used for merging dataframes : merge(), join(), concat()

In [5]:
# merge() function
df1 = pd.DataFrame({'ID' : [1,2,3], 'DreamCompany' : ["Google", "Nvidia", "Accenture"], "Role" : ["DA", "DS", "TL"]})
df2 = pd.DataFrame({"ID" : [2,3,4], 'DreamPackage' : [20, 24, 50]})
print(df1)
print(df2)

   ID DreamCompany Role
0   1       Google   DA
1   2       Nvidia   DS
2   3    Accenture   TL
   ID  DreamPackage
0   2            20
1   3            24
2   4            50

In [6]:
# merge() function behaves like joins in sql
# by default, merge() function perform inner join like operation
# inner merge: common records from both the data frames
merge_df = pd.merge(df1, df2, on = "ID")
merge_df

   ID DreamCompany Role  DreamPackage
0   2       Nvidia   DS            20
1   3    Accenture   TL            24

In [7]:
# left merge: pick all records from left table and common records from the right table
merge_df = pd.merge(df1, df2, on = "ID", how = "left")
merge_df

   ID DreamCompany Role  DreamPackage
0   1       Google   DA           NaN
1   2       Nvidia   DS          20.0
2   3    Accenture   TL          24.0

In [8]:
df2

   ID  DreamPackage
0   2            20
1   3            24
2   4            50

In [9]:
# outer merge : pick all records from right table and left table
# common records will be consider one time only
merge_df = pd.merge(df1, df2, on = "ID", how = "outer")
merge_df

   ID DreamCompany Role  DreamPackage
0   1       Google   DA           NaN
1   2       Nvidia   DS          20.0
2   3    Accenture   TL          24.0
3   4          NaN  NaN          50.0

### join()

# join() is mainly based upon the index value

In [10]:
df3 = pd.DataFrame({"Name_richest" : ["Ambani", "Elon", "Niranjan", "Larry"]}, index = [10,20,30,40])
df4 = pd.DataFrame({"Ntework" : [10, 15, 500, 2]}, index = [20, 30, 40, 50])

joined_df = df3.join(df4, how = "inner")
joined_df

   Name_richest  Ntework
20         Elon       10
30     Niranjan       15
40        Larry      500

In [11]:
joined_df = df3.join(df4, how = "left")
joined_df

   Name_richest  Ntework
10       Ambani      NaN
20         Elon     10.0
30     Niranjan     15.0
40        Larry    500.0

In [12]:
joined_df = df3.join(df4, how = "right")
joined_df

   Name_richest  Ntework
20         Elon       10
30     Niranjan       15
40        Larry      500
50          NaN        2

In [15]:
joined_df = df3.join(df4, how = "outer")
joined_df

   Name_richest  Ntework
10       Ambani      NaN
20         Elon     10.0
30     Niranjan     15.0
40        Larry    500.0
50          NaN      2.0

### concat()

In [14]:
# concat(): merge the dataframes vertically and horizontally
# axis = 0 -> concatinating vertically (increase the rows)
# axis = 1 -> concatinating horizontally (

In [16]:
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["Kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], " Movie" : ["Titanic", "Spiderman"]})
df6

   ID      Movie
0   3    Titanic
1   4  Spiderman

In [17]:
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["Kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], " Movie" : ["Titanic", "Spiderman"]})
df5

   ID          Movie
0   1  Kobbari matta
1   2       Paradise

In [19]:
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["Kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], " Movie" : ["Titanic", "Spiderman"]})

concat_df = pd.concat([df5, df6], axis = 0)
concat_df

   ID          Movie      Movie
0   1  Kobbari matta        NaN
1   2       Paradise        NaN
0   3            NaN    Titanic
1   4            NaN  Spiderman

In [20]:
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["Kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], " Movie" : ["Titanic", "Spiderman"]})

concat_df = pd.concat([df5, df6], axis = 1)
concat_df

   ID          Movie  ID      Movie
0   1  Kobbari matta   3    Titanic
1   2       Paradise   4  Spiderman

In [21]:
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["Kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], " Movie" : ["Titanic", "Spiderman"]})
df7 = pd.DataFrame({"ID" : [5,6], "Movie" : ["Dhurandhar", "Kalank"]})

concat_df = pd.concat([df5, df6, df7], axis = 1)
concat_df

   ID          Movie  ID      Movie  ID       Movie
0   1  Kobbari matta   3    Titanic   5  Dhurandhar
1   2       Paradise   4  Spiderman   6      Kalank

In [23]:
df5 = pd.DataFrame({"ID" : [1,2], "Movie" : ["Kobbari matta", "Paradise"]})
df6 = pd.DataFrame({"ID" : [3,4], " Movie" : ["Titanic", "Spiderman"]})
df7 = pd.DataFrame({"ID" : [5,6], "Movie" : ["Dhurandhar", "Kalank"]})

concat_df = pd.concat([df5, df6, df7], axis = 0, ignore_index = True)
concat_df

   ID          Movie      Movie
0   1  Kobbari matta        NaN
1   2       Paradise        NaN
2   3            NaN    Titanic
3   4            NaN  Spiderman
4   5     Dhurandhar        NaN
5   6         Kalank        NaN

# 10. Time Series operations

In [25]:
# these operations we perform on date and time data

In [26]:
date_rng = pd.date_range(start = '2021-01-01', end = '2026-12-31', freq = 'h')
date_rng

DatetimeIndex(['2021-01-01 00:00:00', '2021-01-01 01:00:00',
               '2021-01-01 02:00:00', '2021-01-01 03:00:00',
               '2021-01-01 04:00:00', '2021-01-01 05:00:00',
               '2021-01-01 06:00:00', '2021-01-01 07:00:00',
               '2021-01-01 08:00:00', '2021-01-01 09:00:00',
               ...
               '2026-12-30 15:00:00', '2026-12-30 16:00:00',
               '2026-12-30 17:00:00', '2026-12-30 18:00:00',
               '2026-12-30 19:00:00', '2026-12-30 20:00:00',
               '2026-12-30 21:00:00', '2026-12-30 22:00:00',
               '2026-12-30 23:00:00', '2026-12-31 00:00:00'],
              dtype='datetime64[ns]', length=52561, freq='h')

In [28]:
# pick the 1000 records only
import numpy as np

random_dates = np.random.choice(date_rng, size = 1000, replace = False)
print(len(random_dates))

1000

In [32]:
# Creating dataframe using random_dates
canteen_df = pd.DataFrame({
    'timestamp' : pd.to_datetime(random_dates),
    'order_id' : np.arange(1,1001),
    'food_category' : np.random.choice(["Samosa", "Egg puff", "Drinks", "Chocolates", "Irani_tea"], size = 1000),
    'Price' : np.random.randint(10, 500, size = 1000),
    'quantity' : np.random.randint(1, 5, size = 1000)
})

canteen_df

# pd.to_datetime :  to convert numpy array to pandas date_time format
# np.arange : genarate a series of elements e.g 1, 2, 3, 4,5 ....1000
# random.choice : used to

              timestamp  order_id food_category  Price  quantity
0   2021-08-11 07:00:00         1        Drinks    154         4
1   2022-07-21 04:00:00         2        Samosa    413         1
2   2023-10-15 13:00:00         3    Chocolates    218         3
3   2023-12-30 06:00:00         4        Samosa     88         1
4   2021-07-07 10:00:00         5        Drinks     14         2
..                  ...       ...           ...    ...       ...
995 2025-09-08 11:00:00       996     Irani_tea    465         4
996 2023-12-06 03:00:00       997        Samosa    470         2
997 2025-04-14 06:00:00       998    Chocolates    260         4
998 2024-07-15 11:00:00       999        Samosa    154         2
999 2026-01-01 17:00:00      1000        Drinks     65         2

[1000 rows x 5 columns]